### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by cadusilva** [amosbatista/ursal-acessivel#7]
Pouco tempo após iniciar os trabalhos, dá o erro mencionado no título e a partir daí fica preso nisso. Nos logs, a URL que ele tenta puxar informações retorna zero dados. Mas se eu diminuir 1 número do ID, os dados aparecem.

<details>
<summary>Log com muitas linhas</summary>

```
Nov 07 10:41:11 bolha run[3733049]: erro na requisição timeline TypeError: Cannot read properties of undefined (reading 'id')
Nov 07 10:41:11 bolha run[3733049]:     at /home/mastodon/acessivel/dist/timeline/Timeline.Mastodon.service.js:28:56
Nov 07 10:41:11 bolha run[3733049]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 07 10:41:11 bolha run[3733049]:     at async TimelineMastodonService.LoadTimeline (/home/mastodon/acessivel/dist/timeline/Timeline.Mastodon.service.js:18:17)
Nov 07 10:42:41 bolha run[3733049]: Item capturado: undefined
Nov 07 10:42:41 bolha run[3733049]: lista de retorno vazia
Nov 07 10:42:41 bolha run[3733049]: iniciando listagem timeline https://bolha.one/api/v1/timelines/public?local=true&only_media=true&limit=40
Nov 07 10:42:41 bolha run[3733049]:       &min_id=111369508988014361
Nov 07 10:42:41 bolha run[3733049]: Obj response com problemas {
Nov 07 10:42:41 bolha run[3733049]:   status: 200,
Nov 07 10:42:41 bolha run[3733049]:   statusText: 'OK',
Nov 07 10:42:41 bolha run[3733049]:   headers: AxiosHeaders {
Nov 07 10:42:41 bolha run[3733049]:     date: 'Tue, 07 Nov 2023 13:42:41 GMT',
Nov 07 10:42:41 bolha run[3733049]:     'content-type': 'application/json; charset=utf-8',
Nov 07 10:42:41 bolha run[3733049]:     'content-length': '2',
Nov 07 10:42:41 bolha run[3733049]:     connection: 'keep-alive',
Nov 07 10:42:41 bolha run[3733049]:     server: 'Bolha Web Server',
Nov 07 10:42:41 bolha run[3733049]:     'x-frame-options': 'SAMEORIGIN',
Nov 07 10:42:41 bolha run[3733049]:     'x-content-type-options': 'nosniff',
Nov 07 10:42:41 bolha run[3733049]:     'x-xss-protection': '1; mode=block',
Nov 07 10:42:41 bolha run[3733049]:     'referrer-policy': 'strict-origin-when-cross-origin',
Nov 07 10:42:41 bolha run[3733049]:     'x-ratelimit-limit': '300',
Nov 07 10:42:41 bolha run[3733049]:     'x-ratelimit-remaining': '288',
Nov 07 10:42:41 bolha run[3733049]:     'x-ratelimit-reset': '2023-11-07T13:45:00.448572Z',
Nov 07 10:42:41 bolha run[3733049]:     'cache-control': 'max-age=15, public, stale-while-revalidate=30, stale-if-error=86400',
Nov 07 10:42:41 bolha run[3733049]:     etag: 'W/"XYZXYZXYZ"',
Nov 07 10:42:41 bolha run[3733049]:     'content-security-policy': "default-src 'none'; frame-ancestors 'none'; form-action 'none'",
Nov 07 10:42:41 bolha run[3733049]:     'x-request-id': 'XYZXYZXYZ',
Nov 07 10:42:41 bolha run[3733049]:     'x-runtime': '0.029106',
Nov 07 10:42:41 bolha run[3733049]:     'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
Nov 07 10:42:41 bolha run[3733049]:     vary: 'Authorization, Origin',
Nov 07 10:42:41 bolha run[3733049]:     'x-cached': 'EXPIRED'
Nov 07 10:42:41 bolha run[3733049]:   },
Nov 07 10:42:41 bolha run[3733049]:   config: {
Nov 07 10:42:41 bolha run[3733049]:     transitional: {
Nov 07 10:42:41 bolha run[3733049]:       silentJSONParsing: true,
Nov 07 10:42:41 bolha run[3733049]:       forcedJSONParsing: true,
Nov 07 10:42:41 bolha run[3733049]:       clarifyTimeoutError: false
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     adapter: [ 'xhr', 'http' ],
Nov 07 10:42:41 bolha run[3733049]:     transformRequest: [ [Function: transformRequest] ],
Nov 07 10:42:41 bolha run[3733049]:     transformResponse: [ [Function: transformResponse] ],
Nov 07 10:42:41 bolha run[3733049]:     timeout: 0,
Nov 07 10:42:41 bolha run[3733049]:     xsrfCookieName: 'XSRF-TOKEN',
Nov 07 10:42:41 bolha run[3733049]:     xsrfHeaderName: 'X-XSRF-TOKEN',
Nov 07 10:42:41 bolha run[3733049]:     maxContentLength: -1,
Nov 07 10:42:41 bolha run[3733049]:     maxBodyLength: -1,
Nov 07 10:42:41 bolha run[3733049]:     env: { FormData: [Function], Blob: [class Blob] },
Nov 07 10:42:41 bolha run[3733049]:     validateStatus: [Function: validateStatus],
Nov 07 10:42:41 bolha run[3733049]:     headers: AxiosHeaders {
Nov 07 10:42:41 bolha run[3733049]:       Accept: 'application/json, text/plain, */*',
Nov 07 10:42:41 bolha run[3733049]:       Autorizathion: 'Bearer XYZXYZXYZ',
Nov 07 10:42:41 bolha run[3733049]:       'User-Agent': 'axios/1.3.2',
Nov 07 10:42:41 bolha run[3733049]:       'Accept-Encoding': 'gzip, compress, deflate, br'
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     method: 'get',
Nov 07 10:42:41 bolha run[3733049]:     url: 'https://bolha.one/api/v1/timelines/public?local=true&only_media=true&limit=40\n' +
Nov 07 10:42:41 bolha run[3733049]:       '      &min_id=111369508988014361 ',
Nov 07 10:42:41 bolha run[3733049]:     data: undefined
Nov 07 10:42:41 bolha run[3733049]:   },
Nov 07 10:42:41 bolha run[3733049]:   request: <ref *1> ClientRequest {
Nov 07 10:42:41 bolha run[3733049]:     _events: [Object: null prototype] {
Nov 07 10:42:41 bolha run[3733049]:       abort: [Function (anonymous)],
Nov 07 10:42:41 bolha run[3733049]:       aborted: [Function (anonymous)],
Nov 07 10:42:41 bolha run[3733049]:       connect: [Function (anonymous)],
Nov 07 10:42:41 bolha run[3733049]:       error: [Function (anonymous)],
Nov 07 10:42:41 bolha run[3733049]:       socket: [Function (anonymous)],
Nov 07 10:42:41 bolha run[3733049]:       timeout: [Function (anonymous)],
Nov 07 10:42:41 bolha run[3733049]:       finish: [Function: requestOnFinish]
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     _eventsCount: 7,
Nov 07 10:42:41 bolha run[3733049]:     _maxListeners: undefined,
Nov 07 10:42:41 bolha run[3733049]:     outputData: [],
Nov 07 10:42:41 bolha run[3733049]:     outputSize: 0,
Nov 07 10:42:41 bolha run[3733049]:     writable: true,
Nov 07 10:42:41 bolha run[3733049]:     destroyed: true,
Nov 07 10:42:41 bolha run[3733049]:     _last: true,
Nov 07 10:42:41 bolha run[3733049]:     chunkedEncoding: false,
Nov 07 10:42:41 bolha run[3733049]:     shouldKeepAlive: true,
Nov 07 10:42:41 bolha run[3733049]:     maxRequestsOnConnectionReached: false,
Nov 07 10:42:41 bolha run[3733049]:     _defaultKeepAlive: true,
Nov 07 10:42:41 bolha run[3733049]:     useChunkedEncodingByDefault: false,
Nov 07 10:42:41 bolha run[3733049]:     sendDate: false,
Nov 07 10:42:41 bolha run[3733049]:     _removedConnection: false,
Nov 07 10:42:41 bolha run[3733049]:     _removedContLen: false,
Nov 07 10:42:41 bolha run[3733049]:     _removedTE: false,
Nov 07 10:42:41 bolha run[3733049]:     strictContentLength: false,
Nov 07 10:42:41 bolha run[3733049]:     _contentLength: 0,
Nov 07 10:42:41 bolha run[3733049]:     _hasBody: true,
Nov 07 10:42:41 bolha run[3733049]:     _trailer: '',
Nov 07 10:42:41 bolha run[3733049]:     finished: true,
Nov 07 10:42:41 bolha run[3733049]:     _headerSent: true,
Nov 07 10:42:41 bolha run[3733049]:     _closed: true,
Nov 07 10:42:41 bolha run[3733049]:     socket: TLSSocket {
Nov 07 10:42:41 bolha run[3733049]:       _tlsOptions: [Object],
Nov 07 10:42:41 bolha run[3733049]:       _secureEstablished: true,
Nov 07 10:42:41 bolha run[3733049]:       _securePending: false,
Nov 07 10:42:41 bolha run[3733049]:       _newSessionPending: false,
Nov 07 10:42:41 bolha run[3733049]:       _controlReleased: true,
Nov 07 10:42:41 bolha run[3733049]:       secureConnecting: false,
Nov 07 10:42:41 bolha run[3733049]:       _SNICallback: null,
Nov 07 10:42:41 bolha run[3733049]:       servername: 'bolha.one',
Nov 07 10:42:41 bolha run[3733049]:       alpnProtocol: false,
Nov 07 10:42:41 bolha run[3733049]:       authorized: true,
Nov 07 10:42:41 bolha run[3733049]:       authorizationError: null,
Nov 07 10:42:41 bolha run[3733049]:       encrypted: true,
Nov 07 10:42:41 bolha run[3733049]:       _events: [Object: null prototype],
Nov 07 10:42:41 bolha run[3733049]:       _eventsCount: 9,
Nov 07 10:42:41 bolha run[3733049]:       connecting: false,
Nov 07 10:42:41 bolha run[3733049]:       _hadError: false,
Nov 07 10:42:41 bolha run[3733049]:       _parent: null,
Nov 07 10:42:41 bolha run[3733049]:       _host: 'bolha.one',
Nov 07 10:42:41 bolha run[3733049]:       _closeAfterHandlingError: false,
Nov 07 10:42:41 bolha run[3733049]:       _readableState: [ReadableState],
Nov 07 10:42:41 bolha run[3733049]:       _maxListeners: undefined,
Nov 07 10:42:41 bolha run[3733049]:       _writableState: [WritableState],
Nov 07 10:42:41 bolha run[3733049]:       allowHalfOpen: false,
Nov 07 10:42:41 bolha run[3733049]:       _sockname: null,
Nov 07 10:42:41 bolha run[3733049]:       _pendingData: null,
Nov 07 10:42:41 bolha run[3733049]:       _pendingEncoding: '',
Nov 07 10:42:41 bolha run[3733049]:       server: undefined,
Nov 07 10:42:41 bolha run[3733049]:       _server: null,
Nov 07 10:42:41 bolha run[3733049]:       ssl: [TLSWrap],
Nov 07 10:42:41 bolha run[3733049]:       _requestCert: true,
Nov 07 10:42:41 bolha run[3733049]:       _rejectUnauthorized: true,
Nov 07 10:42:41 bolha run[3733049]:       timeout: 5000,
Nov 07 10:42:41 bolha run[3733049]:       parser: null,
Nov 07 10:42:41 bolha run[3733049]:       _httpMessage: null,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(alpncallback)]: null,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(res)]: [TLSWrap],
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(verified)]: true,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(pendingSession)]: null,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(async_id_symbol)]: -1,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kHandle)]: [TLSWrap],
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(lastWriteQueueSize)]: 0,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(timeout)]: Timeout {
Nov 07 10:42:41 bolha run[3733049]:         _idleTimeout: 5000,
Nov 07 10:42:41 bolha run[3733049]:         _idlePrev: [TimersList],
Nov 07 10:42:41 bolha run[3733049]:         _idleNext: [TimersList],
Nov 07 10:42:41 bolha run[3733049]:         _idleStart: 360580,
Nov 07 10:42:41 bolha run[3733049]:         _onTimeout: [Function: bound ],
Nov 07 10:42:41 bolha run[3733049]:         _timerArgs: undefined,
Nov 07 10:42:41 bolha run[3733049]:         _repeat: null,
Nov 07 10:42:41 bolha run[3733049]:         _destroyed: false,
Nov 07 10:42:41 bolha run[3733049]:         [Symbol(refed)]: false,
Nov 07 10:42:41 bolha run[3733049]:         [Symbol(kHasPrimitive)]: false,
Nov 07 10:42:41 bolha run[3733049]:         [Symbol(asyncId)]: 116,
Nov 07 10:42:41 bolha run[3733049]:         [Symbol(triggerId)]: 114
Nov 07 10:42:41 bolha run[3733049]:       },
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kBuffer)]: null,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kBufferCb)]: null,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kBufferGen)]: null,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kCapture)]: false,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kSetNoDelay)]: false,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kSetKeepAlive)]: true,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kSetKeepAliveInitialDelay)]: 1,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kBytesRead)]: 0,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kBytesWritten)]: 0,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(connect-options)]: [Object]
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     _header: 'GET /api/v1/timelines/public?local=true&only_media=true&limit=40%20%20%20%20%20%20&min_id=111369508988014361 HTTP/1.1\r\n' +
Nov 07 10:42:41 bolha run[3733049]:       'Accept: application/json, text/plain, */*\r\n' +
Nov 07 10:42:41 bolha run[3733049]:       'Autorizathion: Bearer XYZXYZXYZ\r\n' +
Nov 07 10:42:41 bolha run[3733049]:       'User-Agent: axios/1.3.2\r\n' +
Nov 07 10:42:41 bolha run[3733049]:       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
Nov 07 10:42:41 bolha run[3733049]:       'Host: bolha.one\r\n' +
Nov 07 10:42:41 bolha run[3733049]:       'Connection: keep-alive\r\n' +
Nov 07 10:42:41 bolha run[3733049]:       '\r\n',
Nov 07 10:42:41 bolha run[3733049]:     _keepAliveTimeout: 0,
Nov 07 10:42:41 bolha run[3733049]:     _onPendingData: [Function: nop],
Nov 07 10:42:41 bolha run[3733049]:     agent: Agent {
Nov 07 10:42:41 bolha run[3733049]:       _events: [Object: null prototype],
Nov 07 10:42:41 bolha run[3733049]:       _eventsCount: 2,
Nov 07 10:42:41 bolha run[3733049]:       _maxListeners: undefined,
Nov 07 10:42:41 bolha run[3733049]:       defaultPort: 443,
Nov 07 10:42:41 bolha run[3733049]:       protocol: 'https:',
Nov 07 10:42:41 bolha run[3733049]:       options: [Object: null prototype],
Nov 07 10:42:41 bolha run[3733049]:       requests: [Object: null prototype] {},
Nov 07 10:42:41 bolha run[3733049]:       sockets: [Object: null prototype] {},
Nov 07 10:42:41 bolha run[3733049]:       freeSockets: [Object: null prototype],
Nov 07 10:42:41 bolha run[3733049]:       keepAliveMsecs: 1000,
Nov 07 10:42:41 bolha run[3733049]:       keepAlive: true,
Nov 07 10:42:41 bolha run[3733049]:       maxSockets: Infinity,
Nov 07 10:42:41 bolha run[3733049]:       maxFreeSockets: 256,
Nov 07 10:42:41 bolha run[3733049]:       scheduling: 'lifo',
Nov 07 10:42:41 bolha run[3733049]:       maxTotalSockets: Infinity,
Nov 07 10:42:41 bolha run[3733049]:       totalSocketCount: 1,
Nov 07 10:42:41 bolha run[3733049]:       maxCachedSessions: 100,
Nov 07 10:42:41 bolha run[3733049]:       _sessionCache: [Object],
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kCapture)]: false
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     socketPath: undefined,
Nov 07 10:42:41 bolha run[3733049]:     method: 'GET',
Nov 07 10:42:41 bolha run[3733049]:     maxHeaderSize: undefined,
Nov 07 10:42:41 bolha run[3733049]:     insecureHTTPParser: undefined,
Nov 07 10:42:41 bolha run[3733049]:     joinDuplicateHeaders: undefined,
Nov 07 10:42:41 bolha run[3733049]:     path: '/api/v1/timelines/public?local=true&only_media=true&limit=40%20%20%20%20%20%20&min_id=111369508988014361',
Nov 07 10:42:41 bolha run[3733049]:     _ended: true,
Nov 07 10:42:41 bolha run[3733049]:     res: IncomingMessage {
Nov 07 10:42:41 bolha run[3733049]:       _readableState: [ReadableState],
Nov 07 10:42:41 bolha run[3733049]:       _events: [Object: null prototype],
Nov 07 10:42:41 bolha run[3733049]:       _eventsCount: 4,
Nov 07 10:42:41 bolha run[3733049]:       _maxListeners: undefined,
Nov 07 10:42:41 bolha run[3733049]:       socket: null,
Nov 07 10:42:41 bolha run[3733049]:       httpVersionMajor: 1,
Nov 07 10:42:41 bolha run[3733049]:       httpVersionMinor: 1,
Nov 07 10:42:41 bolha run[3733049]:       httpVersion: '1.1',
Nov 07 10:42:41 bolha run[3733049]:       complete: true,
Nov 07 10:42:41 bolha run[3733049]:       rawHeaders: [Array],
Nov 07 10:42:41 bolha run[3733049]:       rawTrailers: [],
Nov 07 10:42:41 bolha run[3733049]:       joinDuplicateHeaders: undefined,
Nov 07 10:42:41 bolha run[3733049]:       aborted: false,
Nov 07 10:42:41 bolha run[3733049]:       upgrade: false,
Nov 07 10:42:41 bolha run[3733049]:       url: '',
Nov 07 10:42:41 bolha run[3733049]:       method: null,
Nov 07 10:42:41 bolha run[3733049]:       statusCode: 200,
Nov 07 10:42:41 bolha run[3733049]:       statusMessage: 'OK',
Nov 07 10:42:41 bolha run[3733049]:       client: [TLSSocket],
Nov 07 10:42:41 bolha run[3733049]:       _consuming: false,
Nov 07 10:42:41 bolha run[3733049]:       _dumped: false,
Nov 07 10:42:41 bolha run[3733049]:       req: [Circular *1],
Nov 07 10:42:41 bolha run[3733049]:       responseUrl: 'https://bolha.one/api/v1/timelines/public?local=true&only_media=true&limit=40%20%20%20%20%20%20&min_id=111369508988014361',
Nov 07 10:42:41 bolha run[3733049]:       redirects: [],
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kCapture)]: false,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kHeaders)]: [Object],
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kHeadersCount)]: 40,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kTrailers)]: null,
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kTrailersCount)]: 0
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     aborted: false,
Nov 07 10:42:41 bolha run[3733049]:     timeoutCb: null,
Nov 07 10:42:41 bolha run[3733049]:     upgradeOrConnect: false,
Nov 07 10:42:41 bolha run[3733049]:     parser: null,
Nov 07 10:42:41 bolha run[3733049]:     maxHeadersCount: null,
Nov 07 10:42:41 bolha run[3733049]:     reusedSocket: false,
Nov 07 10:42:41 bolha run[3733049]:     host: 'bolha.one',
Nov 07 10:42:41 bolha run[3733049]:     protocol: 'https:',
Nov 07 10:42:41 bolha run[3733049]:     _redirectable: Writable {
Nov 07 10:42:41 bolha run[3733049]:       _writableState: [WritableState],
Nov 07 10:42:41 bolha run[3733049]:       _events: [Object: null prototype],
Nov 07 10:42:41 bolha run[3733049]:       _eventsCount: 3,
Nov 07 10:42:41 bolha run[3733049]:       _maxListeners: undefined,
Nov 07 10:42:41 bolha run[3733049]:       _options: [Object],
Nov 07 10:42:41 bolha run[3733049]:       _ended: true,
Nov 07 10:42:41 bolha run[3733049]:       _ending: true,
Nov 07 10:42:41 bolha run[3733049]:       _redirectCount: 0,
Nov 07 10:42:41 bolha run[3733049]:       _redirects: [],
Nov 07 10:42:41 bolha run[3733049]:       _requestBodyLength: 0,
Nov 07 10:42:41 bolha run[3733049]:       _requestBodyBuffers: [],
Nov 07 10:42:41 bolha run[3733049]:       _onNativeResponse: [Function (anonymous)],
Nov 07 10:42:41 bolha run[3733049]:       _currentRequest: [Circular *1],
Nov 07 10:42:41 bolha run[3733049]:       _currentUrl: 'https://bolha.one/api/v1/timelines/public?local=true&only_media=true&limit=40%20%20%20%20%20%20&min_id=111369508988014361',
Nov 07 10:42:41 bolha run[3733049]:       [Symbol(kCapture)]: false
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(kCapture)]: false,
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(kBytesWritten)]: 0,
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(kNeedDrain)]: false,
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(corked)]: 0,
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(kOutHeaders)]: [Object: null prototype] {
Nov 07 10:42:41 bolha run[3733049]:       accept: [Array],
Nov 07 10:42:41 bolha run[3733049]:       autorizathion: [Array],
Nov 07 10:42:41 bolha run[3733049]:       'user-agent': [Array],
Nov 07 10:42:41 bolha run[3733049]:       'accept-encoding': [Array],
Nov 07 10:42:41 bolha run[3733049]:       host: [Array]
Nov 07 10:42:41 bolha run[3733049]:     },
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(errored)]: null,
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(kHighWaterMark)]: 16384,
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(kRejectNonStandardBodyWrites)]: false,
Nov 07 10:42:41 bolha run[3733049]:     [Symbol(kUniqueHeaders)]: null
Nov 07 10:42:41 bolha run[3733049]:   },
Nov 07 10:42:41 bolha run[3733049]:   data: []
Nov 07 10:42:41 bolha run[3733049]: }
Nov 07 10:42:41 bolha run[3733049]: erro na requisição timeline TypeError: Cannot read properties of undefined (reading 'id')
Nov 07 10:42:41 bolha run[3733049]:     at /home/mastodon/acessivel/dist/timeline/Timeline.Mastodon.service.js:28:56
Nov 07 10:42:41 bolha run[3733049]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 07 10:42:41 bolha run[3733049]:     at async TimelineMastodonService.LoadTimeline (/home/mastodon/acessivel/dist/timeline/Timeline.Mastodon.service.js:18:17)
```
</details>

URL com ID `111369508988014361`:

```
[]
```

URL com ID `111369508988014360`: 

```
[{"id":"111369508988014361","created_at":"2023-11-07T13:30:45.641Z","in_reply_to_id (...)
```

**Comment by amosbatista** [comment]
Olá, Cadú.

Infelizmente este é um erro que eu não tive tempo de cobrir.

Ele ocorre quando a timeline chega no toot mais novo, e não há mais toots para verificar. Não é um erro, mas a API do MAstodom retorna erro.

Eu precisava tratar este retorno e não tive tempo.

**Comment by cadusilva** [comment]
> Olá, Cadú.
> 
> Infelizmente este é um erro que eu não tive tempo de cobrir.
> 
> Ele ocorre quando a timeline chega no toot mais novo, e não há mais toots para verificar. Não é um erro, mas a API do MAstodom retorna erro.
> 
> Eu precisava tratar este retorno e não tive tempo.

Sem problemas, mas mesmo com esse comportamento o robozinho ainda consegue fazer o trabalho dele conforme chegam toots novos? A Bolha é uma instância pequena mesmo, esperado que o robô logo fique sem toots novos após checar todos.

**Comment by amosbatista** [comment]
Sim, é um processo automático.

**Comment by cadusilva** [comment]
> Sim, é um processo automático.

Ótimo, então por enquanto vou apenas ignorar os erros.

E muito obrigado pelo trabalho feito com o robozinho!
